
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: fastly/compute-starter-kit-rust-fanout
  description: Fanout package template for Rust based Fastly Compute projects.
  name: compute-starter-kit-rust-fanout
  title: fastly/compute-starter-kit-rust-fanout
spec:
  lifecycle: source
  owner: group:fanout
  type: repository
