authors = ["<oss@fastly.com>"]
description = "Implements Fanout handlers for WebSockets, SSE, etc."
language = "rust"
manifest_version = 2
name = "Push messaging using Fanout"

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"
