name = "Push messaging using Fanout"
description = "Implements Fanout handlers for WebSockets, SSE, etc."
authors = ["<devrel@fastly.com>"]
language = "rust"
manifest_version = 3

[scripts]
  build = "cargo build --profile release"
